### ISSUE TITLE
Add Assembly Tutorial Starter Project

### ISSUE THREAD

**Issue by dnhuch** [Vantiq/Contributions#13]
Add the project used at the start of the assembly tutorial

**Comment by dnhuch** [comment]
For step 1 of the tutorial, you need to import a functioning project that you will convert into an Assembly. We decided to place that project here. The final result of the tutorial (like the other tutorials) will be added to the tutorial repo

**Comment by sfitts** [comment]
OK -- though that still feels a bit funny (this is supposed to be for field contributed examples/code).  Either way, the actual artifact should be merged here (then we zip things up and move them over to the public repo).

**Comment by dnhuch** [comment]
If there's somewhere else we think would make the most sense to put the start project I'm happy to put it anywhere. We can create another public repo and link to it if that'd be better practice

**Comment by sfitts** [comment]
I would have just put it in tutorials as well.  We do *not* need another one of these though.
